version: 0.0
os: linux
files:
  - source: /codedeploydemo/mydeploy.sh
    destination: /tmp/scripts
hooks:
  ApplicationStart:
    - location: /tmp/scripts/mydeploy.sh    
      timeout: 2m
      runas: sudo