version: 0.0
files:
	- source: ./codedeploydemo/mydeploy.sh
    destination: /tmp/scripts
hooks:
  ApplicationStart:
    - location: /tmp/scripts    
      timeout: 
      runas: sh mydeploy.sh
    - location: 
      timeout:
      runas:
